name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"   # diario 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Akradeveloper
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid

          # Repos (aquí es donde saca “datos de todos los repos”)
          plugin_repositories: yes
          plugin_repositories_featured: Selenium-FW, Selenium-exercises, Hipos
          plugin_repositories_pinned: 0
          plugin_repositories_affiliations: owner
          plugin_repositories_sort: stargazers
          plugin_repositories_limit: 100

          # Lenguajes / líneas / etc.
          plugin_languages: yes
          plugin_languages_limit: 10
          plugin_languages_details: bytes-size, percentage

          # Diseño dark
          config_display: large
          config_padding: 8%
          config_output: github-metrics.svg
